name: Simatic Edge Node-RED # Name of the Catalog Entry
description: |
  Siemens custom build Node-RED.
version: 0.9.7.21 # Version of the Catalog to be used
category: Applications # Category to be used for searching catalog entries
Support: Siemens
maintainer: Siemens # The maintainer of the catalog entry
license: None # The license
projectURL: https://code.siemens.com/sim-edge-modules/sim-edge-platform-node-red # A URL related to the catalog entry
